import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";

export interface ResolveVersionOptions {
  /**
   * Root directory of the plugin (defaults to `process.cwd()`).
   */
  cwd?: string;

  /**
   * Whether to augment development versions with git commit short hash
   * (e.g. "0.1.0-dev.bfe901a" if not an exact tag).
   * Defaults to `true`.
   */
  includeGit?: boolean;

  /**
   * Fallback string if neither package.json nor git metadata can be found.
   * Defaults to "0.0.0".
   */
  fallback?: string;
}

/**
 * Finds the nearest package.json starting from directory and moving up.
 */
function findPackageJson(startDir: string): { version?: string; name?: string } | null {
  let current = path.resolve(startDir);
  const root = path.parse(current).root;

  while (current !== root) {
    const pkgPath = path.join(current, "package.json");
    if (fs.existsSync(pkgPath)) {
      try {
        const raw = fs.readFileSync(pkgPath, "utf8");
        return JSON.parse(raw);
      } catch {
        return null;
      }
    }
    const parent = path.dirname(current);
    if (parent === current) break;
    current = parent;
  }

  return null;
}

/**
 * Resolves the plugin version from `package.json`, augmented by Git tag / commit hash.
 *
 * Precedence:
 * 1. Exact Git tag on current commit (e.g. "v0.1.2" or "0.1.2")
 * 2. `package.json` version (augmented with "-dev.hash" if in git and not on an exact release tag)
 * 3. Git commit short hash fallback (e.g. "dev-bfe901a")
 * 4. Fallback string (defaults to "0.0.0")
 */
export function resolvePluginVersion(options: ResolveVersionOptions = {}): string {
  const {
    cwd = process.cwd(),
    includeGit = true,
    fallback = "0.0.0",
  } = options;

  let pkgVersion: string | undefined;

  // 1. Read package.json
  const pkg = findPackageJson(cwd);
  if (pkg?.version) {
    pkgVersion = pkg.version;
  }

  if (!includeGit) {
    return pkgVersion || fallback;
  }

  // 2. Check if git is available and on an exact tag
  try {
    const gitTag = execSync("git describe --tags --exact-match 2>/dev/null", {
      cwd,
      encoding: "utf8",
      timeout: 1000,
    }).trim();

    if (gitTag) {
      // Strip leading 'v' if present for clean semantic format (e.g. "v0.1.2" -> "0.1.2")
      return gitTag.startsWith("v") ? gitTag.slice(1) : gitTag;
    }
  } catch {
    // Not on an exact tag or git not installed
  }

  // 3. If package.json has a version, check if we should add git short commit
  try {
    const gitHash = execSync("git rev-parse --short HEAD 2>/dev/null", {
      cwd,
      encoding: "utf8",
      timeout: 1000,
    }).trim();

    if (gitHash) {
      if (pkgVersion) {
        return `${pkgVersion}+${gitHash}`;
      }
      return `0.0.0+${gitHash}`;
    }
  } catch {
    // Not a git repository
  }

  return pkgVersion || fallback;
}

export interface StampVersionOptions extends ResolveVersionOptions {
  /**
   * Destination TypeScript / JavaScript file path.
   * Defaults to "./version.ts" or "./src/version.ts".
   */
  targetFile?: string;
}

/**
 * Build-time utility to stamp the resolved version into a TypeScript file (e.g. `version.ts`),
 * allowing client code (React Native / Hermes) to import `PLUGIN_VERSION` directly without
 * needing `node:fs` or `process.cwd()` at runtime.
 */
export function stampVersion(options: StampVersionOptions = {}): {
  version: string;
  targetFile: string;
  updated: boolean;
} {
  const cwd = options.cwd ?? process.cwd();
  const targetFile = options.targetFile
    ? path.resolve(cwd, options.targetFile)
    : path.resolve(cwd, "version.ts");

  const version = resolvePluginVersion(options);
  const content = `// Auto-generated by paseo-plugin-helper. Do not edit.\nexport const PLUGIN_VERSION = "${version}";\n`;

  let existing = "";
  if (fs.existsSync(targetFile)) {
    existing = fs.readFileSync(targetFile, "utf8");
  }

  if (existing !== content) {
    fs.mkdirSync(path.dirname(targetFile), { recursive: true });
    fs.writeFileSync(targetFile, content, "utf8");
    return { version, targetFile, updated: true };
  }

  return { version, targetFile, updated: false };
}
